version: "{build}"
os: Windows Server 2012 R2
branches:
  only:
    - master
test: off
deploy: off

install:
  - mkdir -p %LOCALAPPDATA%\glslangValidator
  - appveyor DownloadFile https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Windows/glslangValidator.exe -FileName %LOCALAPPDATA%\glslangValidator\glslangValidator.exe
  - appveyor DownloadFile https://atom.io/download/windows -FileName AtomSetup.exe
  - AtomSetup.exe /silent

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%LOCALAPPDATA%\atom\bin;%LOCALAPPDATA%\glslangValidator;%PATH%
  - atom -v
  - apm -v
  - apm clean
  - apm install
  - apm test
  - glslangValidator -v
