### Project specific config ###
install:
  - mkdir -p %LOCALAPPDATA%\glslangValidator
  - appveyor DownloadFile https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Windows/glslangValidator.exe -FileName %LOCALAPPDATA%\glslangValidator\glslangValidator.exe

environment:
  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

build_script:
  - SET PATH=%LOCALAPPDATA%\glslangValidator;%PATH%
  - glslangValidator -v
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

### Generic setup follows ###
branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
